name: 🤗 Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Push to hub
      - name: Push to hub
        env:
          HUYDN_HF_TOKEN: ${{ secrets.HUYDN_HF_TOKEN }}
        run: git push -f https://tony2802:$HUYDN_HF_TOKEN@huggingface.co/spaces/tony2802/fsa-simpleqt main